from pathlib import Path
import wfdb              # Reading clinical ECG files (standard for .dat and .hea files)
import numpy as np       # Numerical computing and array manipulation
import scipy.signal as signal # The "engine" for filtering (Butterworth, FFT)
import matplotlib.pyplot as plt # Visualizing the biopotential signals
import pandas as pd      # Handling clinical metadata and patient labels
import ast
from scipy.signal import butter, lfilter, filtfilt, iirnotch
import scipy.io

#list of 12 leads in the standard order
LEADS = [
    "I", "II", "III",
    "aVR", "aVL", "aVF",
    "V1", "V2", "V3", "V4", "V5", "V6"
]
# ----------------------------
# Paths
# ----------------------------
#goes to the root directory of the project
ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data"# goes to data folder in the root directory


# ----------------------------
# Load PTB-XL metadata
# ----------------------------

df = pd.read_csv(DATA_PATH / "ptbxl_database.csv")

print("Dataset shape:", df.shape)
print(df.head())


# ----------------------------
# Load your single ECG record
# ----------------------------

record = df.iloc[0]

record_path = DATA_PATH / "00001_hr"

ecg, info = wfdb.rdsamp(str(record_path))


print("\nECG shape:", ecg.shape)
print("Sampling frequency:", info["fs"])
print("Duration:", ecg.shape[0] / info["fs"], "seconds")


# ----------------------------
# Patient information
# ----------------------------

print("\nPatient information:")
print(record[["ecg_id", "patient_id", "age", "sex", "height", "weight",  "site", "device", "recording_date", "report", "scp_codes", "heart_axis", "infarction_stadium1", "infarction_stadium2", "validated_by", "second_opinion", "initial_autogenerated_report", "validated_by_human", "baseline_drift", "static_noise", "burst_noise", "electrodes_problems", "extra_beats", "pacemaker", "strat_fold", "filename_lr", "filename_hr"]])

# ----------------------------
# Decode diagnosis labels
# ----------------------------

df["scp_codes"] = df["scp_codes"].apply(ast.literal_eval)

diagnosis = df.iloc[0]["scp_codes"]

print("\nDiagnosis codes:")
print(diagnosis)

print("\nNormal ECG probability:")
print(diagnosis.get("NORM", 0.0))

# ----------------------------
# Plot 12 ECG leads sampled by index (not time)
# ----------------------------

plt.figure(figsize=(12, 10))

for lead in range(ecg.shape[1]):
    plt.subplot(12, 1, lead + 1)
    plt.plot(ecg[:, lead])
    plt.ylabel(LEADS[lead])

plt.xlabel("Samples")
plt.suptitle("12 Lead ECG")


plt.savefig(
    ROOT / "ecg_12Leadssample.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()
# ----------------------------
# Plot 12 ECG leads sampled by time
# ----------------------------

fs = info["fs"]

time = np.arange(ecg.shape[0]) / fs

plt.figure(figsize=(12, 10))

for lead in range(ecg.shape[1]):
    plt.subplot(12, 1, lead + 1)
    plt.plot(time, ecg[:, lead])
    plt.ylabel(LEADS[lead])

plt.xlabel("Time (seconds)")
plt.suptitle("12 Lead ECG")

plt.savefig(
    ROOT / "ecg_12Leads_time.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()





# ----------------------------
# Focus on single lead: Lead II
# ----------------------------


lead_idx = LEADS.index("II")

lead_II = ecg[:, lead_idx]

time = np.arange(len(lead_II)) / fs

plt.figure(figsize=(12,4))

plt.plot(time, lead_II)
# label 
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude (mV)")
plt.title(f"Lead II ECG — Patient {record['patient_id']}")

plt.grid(True, alpha=0.3)
# save the figure to the root directory with a high resolution
plt.savefig(
    ROOT / "ecg_leadII_raw_time.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
#----------------------------
#step 2 Signal Processing: Filtering and Noise Reduction
#-----------------------------
#define a bandpass filter function
#ecg_signal  = lead_II
# lowcut = 0.5  # Lower cutoff frequency in Hz
# highcut = 40.0  # Upper cutoff frequency in Hz
#sampling rate = info["fs"]  # Sampling rate in Hz
# order = 2  # Order of the filter
#print sampling rate
print("Sampling rate:", info["fs"])
def bandPass_filter(ecg, lowcut, highcut, sampling_rate, order=4):
    nyquist = 0.5 * sampling_rate#500hz*0.5 = 250hz
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = butter(order, [low, high], btype='band')
    y = filtfilt(b, a, ecg)
    return y
lowcut = 0.5  # Lower cutoff frequency in Hz
highcut = 40.0  # Upper cutoff frequency in Hz
bandpassed_ecg = bandPass_filter(lead_II, lowcut, highcut, info["fs"], order=4) 
#notch filter 
def notch_filter(ecg, notch_freq, sampling_rate, quality_factor=30):
    nyquist = 0.5 * sampling_rate
    freq = notch_freq / nyquist
    b, a = iirnotch(freq, quality_factor)
    y = filtfilt(b, a, ecg)
    return y
filtered_ecg = notch_filter(
    bandpassed_ecg,
    notch_freq=50.0,
    sampling_rate=fs,
    quality_factor=30
)
flat_filtered_ecg = filtered_ecg.flatten()
print("Filtered ECG shape:", flat_filtered_ecg.shape)
print("Raw min/max:", np.min(lead_II), np.max(lead_II))
print("Filtered min/max:", np.min(filtered_ecg), np.max(filtered_ecg))

plt.figure(figsize=(12,5))
#plt.plot(time, lead_II, label='Raw ECG', alpha=0.5)
plt.plot(time, filtered_ecg, label='Filtered ECG', color='red')
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude (mV)")
plt.title(f"Lead II ECG — Patient {record['patient_id']} (Filtered)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig(
    ROOT / "ecg_leadII_filtered_time.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
plt.figure(figsize=(12,5))
plt.plot(time, lead_II, label="Raw ECG", alpha=0.5)
plt.plot(time, filtered_ecg, label="Filtered ECG", color="red")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude (mV)")
plt.legend()
plt.grid(True)
plt.savefig(
    ROOT / "ecg_leadII_filtered and_raw_time.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()



