from pathlib import Path
import wfdb              # Reading clinical ECG files (standard for .dat and .hea files)
import numpy as np       # Numerical computing and array manipulation
import scipy.signal as signal # The "engine" for filtering (Butterworth, FFT)
import matplotlib.pyplot as plt # Visualizing the biopotential signals
import pandas as pd      # Handling clinical metadata and patient labels
import ast
from scipy.signal import butter, lfilter, filtfilt, iirnotch


#list of 12 leads in the standard order
LEADS = [
    "I", "II", "III",
    "aVR", "aVL", "aVF",
    "V1", "V2", "V3", "V4", "V5", "V6"
]
# ----------------------------
# Paths
# ----------------------------
#goes to the root directory of the project
ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data"# goes to data folder in the root directory


# ----------------------------
# Load PTB-XL metadata
# ----------------------------

df = pd.read_csv(DATA_PATH / "ptbxl_database.csv")

print("Dataset shape:", df.shape)
print(df.head())


# ----------------------------
# Load your single ECG record
# Note: this is still hardcoded to one demo record, so it does not yet scale
# to batch analysis across multiple PTB-XL samples.
# ----------------------------

record = df.iloc[0]

record_path = DATA_PATH / "00001_hr"  # Hardcoded path; should come from metadata.

ecg, info = wfdb.rdsamp(str(record_path))


print("\nECG shape:", ecg.shape)
print("Sampling frequency:", info["fs"])
print("Duration:", ecg.shape[0] / info["fs"], "seconds")


# ----------------------------
# Patient information
# ----------------------------

print("\nPatient information:")
print(record[["ecg_id", "patient_id", "age", "sex", "height", "weight",  "site", "device", "recording_date", "report", "scp_codes", "heart_axis", "infarction_stadium1", "infarction_stadium2", "validated_by", "second_opinion", "initial_autogenerated_report", "validated_by_human", "baseline_drift", "static_noise", "burst_noise", "electrodes_problems", "extra_beats", "pacemaker", "strat_fold", "filename_lr", "filename_hr"]])

# ----------------------------
# Decode diagnosis labels
# ----------------------------

df["scp_codes"] = df["scp_codes"].apply(ast.literal_eval)

diagnosis = df.iloc[0]["scp_codes"]

print("\nDiagnosis codes:")
print(diagnosis)

print("\nNormal ECG probability:")
print(diagnosis.get("NORM", 0.0))

# ----------------------------
# Plot 12 ECG leads sampled by index (not time)
# ----------------------------

plt.figure(figsize=(12, 10))

for lead in range(ecg.shape[1]):
    plt.subplot(12, 1, lead + 1)
    plt.plot(ecg[:, lead])
    plt.ylabel(LEADS[lead])

plt.xlabel("Samples")
plt.suptitle("12 Lead ECG")


plt.savefig(
    ROOT / "ecg_12Leadssample.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()
# ----------------------------
# Plot 12 ECG leads sampled by time
# ----------------------------

fs = info["fs"]

time = np.arange(ecg.shape[0]) / fs

plt.figure(figsize=(12, 10))

for lead in range(ecg.shape[1]):
    plt.subplot(12, 1, lead + 1)
    plt.plot(time, ecg[:, lead])
    plt.ylabel(LEADS[lead])

plt.xlabel("Time (seconds)")
plt.suptitle("12 Lead ECG")

plt.savefig(
    ROOT / "ecg_12Leads_time.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()





# ----------------------------
# Focus on single lead: Lead II
# ----------------------------


lead_idx = LEADS.index("II")

lead_II = ecg[:, lead_idx]

time = np.arange(len(lead_II)) / fs

plt.figure(figsize=(12,4))

plt.plot(time, lead_II)
# label 
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude (mV)")
plt.title(f"Lead II ECG — Patient {record['patient_id']}")

plt.grid(True, alpha=0.3)
# save the figure to the root directory with a high resolution
plt.savefig(
    ROOT / "ecg_leadII_raw_time.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
# ----------------------------
# Step 2: Frequency Domain Analysis — Raw Signal
# going from time domain to frequency domain using Welch's method
# ----------------------------

# Welch PSD of raw signal
freqs_welch, psd_raw = signal.welch(lead_II, fs=fs, nperseg=1024)

plt.figure(figsize=(12, 5))
plt.semilogy(freqs_welch, psd_raw, label="Raw ECG", alpha=0.7)
plt.xlabel("Frequency (Hz)")
plt.ylabel("Power (mV²/Hz)")
plt.title("Power Spectral Density — Raw Signal")
plt.xlim(0, 150)
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig(ROOT / "ecg_psd_raw.png", dpi=300, bbox_inches="tight")
plt.show()
#----------------------------
#step 3 Signal Processing: Filtering and Noise Reduction
#-----------------------------
#define a bandpass filter function
#ecg_signal  = lead_II
  # Lower cutoff frequency in Hz
 # Upper cutoff frequency in Hz
#sampling rate = info["fs"]  # Sampling rate in Hz
 # Order of the filter
#print sampling rate
print("Sampling rate:", info["fs"])
def bandPass_filter(ecg, lowcut, highcut, sampling_rate, order=4):
    nyquist = 0.5 * sampling_rate#500hz*0.5 = 250hz
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = butter(order, [low, high], btype='band')
    y = filtfilt(b, a, ecg)
    return y
# ----------------------------
# R-peak Detection: simplified Pan-Tompkins-style pipeline
# This is not the full adaptive Pan-Tompkins algorithm yet.
# ----------------------------
lowcut = 0.5  # Lower cutoff frequency in Hz
highcut = 40.0  # Upper cutoff frequency in Hz
bandpassed_ecg = bandPass_filter(lead_II, lowcut, highcut, info["fs"], order=4) 
#notch filter 
def notch_filter(ecg, notch_freq, sampling_rate, quality_factor=30):
    nyquist = 0.5 * sampling_rate
    freq = notch_freq / nyquist
    b, a = iirnotch(freq, quality_factor)
    y = filtfilt(b, a, ecg)
    return y
filtered_ecg = notch_filter(
    bandpassed_ecg,
    notch_freq=50.0,
    sampling_rate=fs,
    quality_factor=30
)
flat_filtered_ecg = filtered_ecg.flatten()

print("Filtered ECG shape:", flat_filtered_ecg.shape)
print("Raw min/max:", np.min(lead_II), np.max(lead_II))
print("Filtered min/max:", np.min(filtered_ecg), np.max(filtered_ecg))

plt.figure(figsize=(12,5))
#plt.plot(time, lead_II, label='Raw ECG', alpha=0.5)
plt.plot(time, filtered_ecg, label='Filtered ECG', color='red')
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude (mV)")
plt.title(f"Lead II ECG — Patient {record['patient_id']} (Filtered)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig(
    ROOT / "ecg_leadII_filtered_time.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
plt.figure(figsize=(12,5))
plt.plot(time, lead_II, label="Raw ECG", alpha=0.5)
plt.plot(time, filtered_ecg, label="Filtered ECG", color="red")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude (mV)")
plt.legend()
plt.grid(True)
plt.savefig(
    ROOT / "ecg_leadII_filtered_and_raw_time.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
# ----------------------------
# Step 4: Frequency Domain Analysis — Filtered Signal
# ----------------------------

freqs_welch, psd_filtered = signal.welch(filtered_ecg, fs=fs, nperseg=1024)

# step4a
# psd only the filtered signal
plt.figure(figsize=(12, 5))
plt.semilogy(freqs_welch, psd_filtered, label="Filtered ECG", color="red")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Power (mV²/Hz)")
plt.title("Power Spectral Density — Filtered Signal")
plt.xlim(0, 150)
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig(ROOT / "ecg_psd_filtered.png", dpi=300, bbox_inches="tight")
plt.show()
#step4b
plt.figure(figsize=(12, 5))
plt.semilogy(freqs_welch, psd_raw, label="Raw ECG", alpha=0.5)
plt.semilogy(freqs_welch, psd_filtered, label="Filtered ECG", color="red")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Power (mV²/Hz)")
plt.title("Power Spectral Density — Raw vs Filtered")
plt.xlim(0, 150)
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig(ROOT / "ecg_psd_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

# ----------------------------
# Step 5: Pan-Tompkins R-peak Detection
# Pan & Tompkins, IEEE TBME, 1985
# ----------------------------

# Simplification note: this block follows the Pan-Tompkins idea, but it is
# still a prototype because it uses a fixed initial threshold and a single
# peak-refinement pass instead of the full adaptive search-back logic.

# Stage 1: Bandpass 5-15 Hz applied to preprocessed signal
# Isolates QRS energy band, rejects P/T waves and residual noise
pt_bandpass = bandPass_filter(filtered_ecg, 5.0, 15.0, fs, order=4)
# Stage 2: Five-point derivative —
# Stage 2: Five-point derivative (Pan & Tompkins, 1985)
# y[n] = (1/8)(2x[n] + x[n-1] - x[n-3] - 2x[n-4])
# Five-point used over two-point for noise robustness
derivative = np.zeros_like(pt_bandpass)#zero matrix of the same shape as pt_bandpass
for i in range(4, len(pt_bandpass)):
    derivative[i] = (1/8) * (
        2*pt_bandpass[i] + 
        pt_bandpass[i-1] - 
        pt_bandpass[i-3] - 
        2*pt_bandpass[i-4]
    )
# Stage 3: Squaring —
# Emphasizes large differences and makes all values positive
squared = derivative ** 2
# Stage 4: Moving Window Integration —
window_size = int(0.150 * fs)  # 150 ms window
window = np.ones(window_size) / window_size # matrix of ones divided by window size
integrated = np.convolve(squared, window, mode='same')# convulution of the squared signal with the moving window
# Stage 5: Adaptive Thresholding and Peak Detection —
threshold = 0.15 * np.max(integrated)  
peaks, _ = signal.find_peaks(
    integrated,
    height=threshold,
    distance=int(0.2*fs)  # 200ms minimum — allows up to 300 bpm
)

# Refine the candidate peaks back onto the filtered ECG.
# Without this step, the heart rate would be computed from envelope maxima,
# not the actual R-peak locations.
search_window_back = int(0.05 * fs)   # 50ms back
search_window_fwd = int(0.15 * fs)    # 150ms forward

true_peaks = []
for p in peaks:
    start = max(0, p - search_window_back)
    end = min(len(filtered_ecg), p + search_window_fwd)
    local_max = start + np.argmax(filtered_ecg[start:end])
    true_peaks.append(local_max)
true_peaks = np.array(true_peaks)

# Remove duplicates that might land on same peak
true_peaks = np.unique(true_peaks)
# Calculate heart rate from R-R intervals
rr_intervals = np.diff(true_peaks) / fs  # in seconds
heart_rate = 60 / np.mean(rr_intervals)  # in bpm
print(f"Detected {len(true_peaks)} R-peaks")
print(f"Mean heart rate: {heart_rate:.1f} bpm")
# Plot detected QRS-peaks
plt.figure(figsize=(12, 5))
plt.plot(time, filtered_ecg, label="Filtered ECG", alpha=0.7)
plt.plot(time[true_peaks], filtered_ecg[true_peaks], "rx", markersize=10, label="R-peaks")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude (mV)")
plt.title("R-peak Detection — Pan-Tompkins")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig(ROOT / "ecg_rpeaks.png", dpi=300, bbox_inches="tight")
plt.show()


